### ISSUE TITLE
datasource.lib is missing

### ISSUE THREAD

**Issue by juzam** [urbiworx/node-red-contrib-freeboard#1]
"datasource.lib" is missing (tried both git repo and npm package)

It's referenced in freeboard.js here:

```
fs.readFile(__dirname+"/datasource.lib", function (err, data) {
    if (err) throw err;
    dslib=data.toString();
});
```

Here's the relevant Node-RED log:
21 Feb 16:02:47 - [red] Uncaught Exception:
21 Feb 16:02:47 - Error: ENOENT, open '/opt/node-red/node_modules/node-red-contr
ib-freeboard/datasource.lib'

**Comment by urbiworx** [comment]
Thanks for your comment, I renamed the file, hopefully that solves the issue?

**Comment by juzam** [comment]
Super. tested the npm package and now everything is ok.
