### ISSUE TITLE
unable to install on RPi

### ISSUE THREAD

**Issue by janeksz** [urbiworx/node-red-contrib-freeboard#19]
root@raspberrypi:~/.node-red# npm install node-red-contrib-freeboard
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/freeboard/freeboard.git /root/.npm/_git-remot.
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/freeboard/freeboard.git /root/.npm/_git-remot:
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/freeboard/freeboard.git /root/.npm/_git-remott
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-red-contrib-freeboard"
npm ERR! node v0.12.13
npm ERR! npm  v2.15.0
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/freeboard/freeboard.git /root9
npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-freeboard-freeboard-git-edbc1d29'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.120]: errno=Connection timed out
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.node-red/npm-debug.log
root@raspberrypi:~/.node-red# npm install node-red-contrib-freeboard
[npm-debug.txt](https://github.com/urbiworx/node-red-contrib-freeboard/files/299816/npm-debug.txt)

**Comment by ivo1981** [comment]
I know it's a bit late but you need to install it in the right location:
cd /usr/lib/node_modules/node-red
sudo npm install node-red-contrib-freeboard.
just tried it on a pi2 with jessie (2016-05-27-raspbian-jessie.img)

**Comment by janeksz** [comment]
thanks, appreciate it.
