### ISSUE TITLE
Installing node-red-contrib-freeboard

### ISSUE THREAD

**Issue by patiltushar023** [urbiworx/node-red-contrib-freeboard#26]
Hi ,

I have installed node-red successfully .its working ,
But now i want to install "node-red-contrib-freeboard".

I followed the instruction on https://www.npmjs.com/package/node-red-contrib-freeboard

but when i hit the "npm install node-red-contrib-freeboard" command in my node red root directory

i get this error :

node-red-contrib-freeboard@0.0.7 postinstall C:\Users\admin.node-red\node_modules\node-red-contrib-freeboard
node rewritefiles.js
{ Error: ENOENT: no such file or directory, open 'C:\Users\admin.node-red\node_modules\node-red-contrib-freeboard\node_modules\freeboard\index.html'
at Error (native)
errno: -4058,
code: 'ENOENT',
syscall: 'open',
path: 'C:\Users\admin\.node-red\node_modules\node-red-contrib-freeboard\node_modules\freeboard\index.html' }
{ Error: ENOENT: no such file or directory, open 'C:\Users\admin.node-red\node_modules\node-red-contrib-freeboard\node_modules\freeboard\js\freeboard.js'
at Error (native)
errno: -4058,
code: 'ENOENT',
syscall: 'open',
path: 'C:\Users\admin\.node-red\node_modules\node-red-contrib-freeboard\node_modules\freeboard\js\freeboard.js' }
events.js:160
throw er; // Unhandled 'error' event

Please help me to make it run.How do i resolve this issue??

Thank you.
![screenshot 6](https://cloud.githubusercontent.com/assets/25752255/22898668/28e0fd7a-f24e-11e6-86f4-1ee8e515f658.png)

**Comment by crouchingbadger** [comment]
I am also getting this when trying today on Ubuntu. I think the package is damaged somehow, but I know nothing about npm:

```bward@new-node-red:~/.node-red$ npm install node-red-contrib-freeboard

> node-red-contrib-freeboard@0.0.7 postinstall /home/bward/.node-red/node_modules/node-red-contrib-freeboard
> node rewritefiles.js

{ Error: ENOENT: no such file or directory, open 'node_modules/freeboard/index.html'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'node_modules/freeboard/index.html' }
{ Error: ENOENT: no such file or directory, open 'node_modules/freeboard/js/freeboard.js'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'node_modules/freeboard/js/freeboard.js' }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'node_modules/freeboard/plugins/thirdparty/jquery.keyframes.min.js'
    at Error (native)
npm WARN enoent ENOENT: no such file or directory, open '/home/bward/.node-red/package.json'
npm WARN .node-red No description
npm WARN .node-red No repository field.
npm WARN .node-red No README data
npm WARN .node-red No license field.
npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-red-contrib-freeboard"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-red-contrib-freeboard@0.0.7 postinstall: `node rewritefiles.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-red-contrib-freeboard@0.0.7 postinstall script 'node rewritefiles.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-red-contrib-freeboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node rewritefiles.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-red-contrib-freeboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-red-contrib-freeboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bward/.node-red/npm-debug.log
```

I can include npm-debug.log if you want.

**Comment by patiltushar023** [comment]
Installation is working ... probably the private network issue.

**Comment by om37** [comment]
What private network issue? I'm having the same problem

**Comment by kleviss** [comment]
same problem here. I dont know why it is not working. any idea how to solve this 3 years later
