### ISSUE TITLE
Does not appeat to work with any version of explorer

### ISSUE THREAD

**Issue by adrianbro** [urbiworx/node-red-contrib-freeboard#3]
Hi the module does not appear to work with any version explorer

**Comment by urbiworx** [comment]
Hi, I am not sure what you are exactly talking about. Do you mean Internet Explorer? Which exact version are you using? What is it that you experience? Did you try it in different browsers?

**Comment by urbiworx** [comment]
I will close this for now, if someone experience the same and has a tip for me this can be reopened.
