### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TotallyInformation** [urbiworx/node-red-contrib-freeboard#6]
Hi, I'm using the latest NR in embedded mode with the NR admin interface appearing under /red.

The link in the help information in my installation shows that freeboard should be accessible under /red/freeboard but it isn't, all I get is the following error message in the browser:

```
Cannot GET /red/freeboard 
```

Can you help please?

**Comment by urbiworx** [comment]
If you have a setting like:
httpNodeRoot: "/api",

then you would find freenode under:
http://localhost:8000/api/freeboard/

**Comment by TotallyInformation** [comment]
Ah! I guess that is the default because I didn't set it.
Perhaps this could be clearer in the documentation? Since that just points people at /freeboard

Thanks.

**Comment by patiltushar023** [comment]
Hi ,

![screenshot 21](https://cloud.githubusercontent.com/assets/25752255/23651340/42a7cc8a-034b-11e7-9afe-d77950d2878e.png)

I have the same issue, but i am using default settings and i am using default url "http://127.0.0.1:1880/freeboard" still i get this error. 

Can you help please?
