### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by nzfarmer1** [urbiworx/node-red-contrib-freeboard#7]
Hi there

Thanks for your great work on this!

Have just come across Freeboard today and set up a framework using web sockets.

As we're using node-red I wondered about integration and found this.

It appears that your approach obviates the need for web sockets for data exchange with Freeboard.  

However, I wonder if you have thought of automating the deployment of edits from Freeboard back via a node-red node?  Having to copy a JSON string to the server after every edit seems to be a weakness (but perhaps I just haven't found an alternative deployment script?).

Thanks

**Comment by urbiworx** [comment]
Hi,

I am not sure if I really understand what you are trying to say.
I think sending the complete config-JSON to the server is the approach that was thought up by the freeboard guys, as this is what I get from the freeboard API. 
Can you maybe elaborate a little what your approach is / would be?

**Comment by urbiworx** [comment]
I will close this for now as I did not hear back.
